# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Deploy on Running Server

on:
  pull_request:
    types: [closed] # when PR closed
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      ## Build Project
    - name: Build with Gradle
      run: ./gradlew build
      # Docker Package 배포
    - name: Publish Image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{ secrets.TOKEN }}
        tag: |
          latest
          ${{github.sha}}
        imageName: release